version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: laravel-app
    environment:
      - DB_HOST=mysql_db
      - DB_DATABASE=tech_dev
      - DB_USERNAME=root
      - DB_PASSWORD=102030
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - mysql_db

  frontend:
    build:
        context: ./frontend
    container_name: react-app
    volumes:
      - ./frontend:/app
    ports:
      - 80:80


  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 102030
      MYSQL_DATABASE: tech_dev
volumes:
  mysql-volume:
    driver: local
