version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: laravel-app
    environment:
      - DB_HOST=mysql_db
      - DB_DATABASE=tech_dev
      - DB_USERNAME=root
      - DB_PASSWORD=102030
    volumes:
      - ./backend:/var/www
    ports:
      - 8000:8000
    depends_on:
      - mysql_db
    command: >
      sh -c "
      composer install &&
      php artisan key:generate &&
      php artisan migrate --force &&
      php -S 0.0.0.0:8000 -t /var/www/public
      "

  frontend:
    build:
      context: ./frontend
    container_name: react-app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true

  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 102030
      MYSQL_DATABASE: tech_dev

volumes:
  mysql-volume:
    driver: local
